PROGRAM DOTP
IMPLICIT NONE
	INTEGER :: I,N
	REAL :: DOT, D
	REAL, DIMENSION(3) :: V1,V2
	N = 3
WRITE(*,*) 'GIVE THE COMPONENTS OF VECTOR1'
DO I = 1,N
	READ(*,*) V1(I)
END DO
WRITE(*,*) 'GIVE THE COMPONENTS OF VECTOR2'
DO I = 1,N
	READ(*,*) V2(I)
END DO
DOT = 0
DO I = 1,n
	D = V1(I)*V2(I)
	DOT = DOT + D
END DO
PRINT*, ' THE DOT PRODUCT OF GIVEN TWO VECTORS IS = ' , DOT
END PROGRAM


